# config.yaml
run_id: tkg-expanded-v1

dirs:
  data: /home/teddy/local/data    # `get_data.sh` will download data to this directory
  proc: kg                        # parent directory for all runs

models:
  vae:       lincsVAE.pt
  deeptraj:  lincsDeepTraj.pt

scripts:
  get_data:     scripts/get_data.sh


# -----------------------------------------------------------------------
# -----------------------------------------------------------------------

make_proc: 
  p_repl:     0.05    # replicate hold-out (test) set proportion
  p_celldrug: 0.02    # cell-drug hold-out (test) set proportion
  p_val:      0.02    # validation set proportion (randomly sampled from training set)
