name: tkgdti
channels:
  - pytorch
  - nvidia
  - pyg
  - conda-forge
dependencies:
  - python
  - pytorch::pytorch
  - pytorch::torchvision
  - pytorch::pytorch-cuda
  - pyg::pyg
  - conda-forge::numpy
  - conda-forge::pandas
  - conda-forge::matplotlib
  - conda-forge::seaborn
  - conda-forge::scikit-learn
  - conda-forge::transformers
  - conda-forge::h5py
  - conda-forge::tensorboard
  - conda-forge::statsmodels
  - conda-forge::pysftp
  - conda-forge::pubchempy
  - snakemake
  - pip
  - pip:
      - ipykernel
      - umap-learn
      - snakemake
      - biopython
      - omnipath
      - pypath-omnipath
      - openpyxl
      - rdkit
      - ogb